#!/bin/zsh
dir="/tmp"
zip="tar.gz"

# NEOVIM
automake="automake-1.17"

 
# DOWNLOAD
curl -o "$dir/$automake.$zip" -OL "https://mirrors.ocf.berkeley.edu/gnu/automake/$automake.$zip"

# UNPACK
tar -xzvf "$dir/$automake.$zip" -C $dir


# INSTALL
cd "$dir/$automake" && ./configure && make && sudo make install # automake

