#!/bin/bash

# Set variables
DMG_URL="https://desktop.figma.com/mac-installer/Figma.dmg"
DMG_NAME="Figma.dmg"
VOLUME_NAME="Figma"

# Download the DMG
curl -L -o "$DMG_NAME" "$DMG_URL"

# Mount the DMG
MOUNT_POINT=$(hdiutil attach "$DMG_NAME" | grep "/Volumes/" | awk '{print $3}')

# Copy the app to /Applications
cp -R "$MOUNT_POINT/Figma.app" /Applications/

# Unmount the DMG
hdiutil detach "$MOUNT_POINT"

# Remove the downloaded DMG
rm "$DMG_NAME"

echo "Figma has been installed to /Applications."

