#!/bin/bash

# Variables
GO_VERSION="1.24.1"
GO_OS="darwin"
GO_ARCH="arm64"
GO_FILE="go${GO_VERSION}.${GO_OS}-${GO_ARCH}.tar.gz"
GO_SHA256="295581b5619acc92f5106e5bcb05c51869337eb19742fdfa6c8346c18e78ff88"
DOWNLOAD_DIR="/tmp"
INSTALL_DIR="/usr/local/go"  # Go convention to install to /usr/local/go
BIN_DIR="/usr/local/bin"

# Download Go archive
echo "Downloading Go archive..."
curl -L "https://go.dev/dl/${GO_FILE}" -o "$DOWNLOAD_DIR/${GO_FILE}"

# Verify SHA256 checksum
echo "Verifying SHA256 checksum..."
ARCHIVE_SHA256=$(shasum -a 256 "$DOWNLOAD_DIR/${GO_FILE}" | awk '{print $1}')

if [ "$ARCHIVE_SHA256" != "$GO_SHA256" ]; then
  echo "SHA256 checksum verification failed!"
  echo "Expected: $GO_SHA256"
  echo "Actual:   $ARCHIVE_SHA256"
  rm "$DOWNLOAD_DIR/${GO_FILE}"
  exit 1
else
  echo "SHA256 checksum verification successful."
fi

# Remove previous installation (if exists)
if [ -d "$INSTALL_DIR" ]; then
    echo "Removing previous Go installation..."
    sudo rm -rf "$INSTALL_DIR"
fi

# Extract Go archive
echo "Extracting Go archive..."
sudo tar -C /usr/local -xzf "$DOWNLOAD_DIR/${GO_FILE}"

# Set environment variables
echo "Setting environment variables..."

# Link go and gofmt binaries to /usr/local/bin
echo "Linking go and gofmt binaries to /usr/local/bin..."
sudo ln -s "$INSTALL_DIR/bin/go" "$BIN_DIR/go"
sudo ln -s "$INSTALL_DIR/bin/gofmt" "$BIN_DIR/gofmt"

# Verify installation
echo "Verifying Go installation..."
if [ -x "$BIN_DIR/go" ]; then
  go version
else
  echo "Go installation failed."
  exit 1
fi

# Clean up
echo "Cleaning up..."
rm "$DOWNLOAD_DIR/${GO_FILE}"

echo "Installation complete!"
echo "Please ensure that /usr/local/bin is in your PATH."

